---

- name: Launch new EC2 instance
  local_action: ec2
      keypair={{ keypair }}
      group={{ security_group }}
      instance_type={{ instance_type }}
      image={{ image }}
      region={{ region }}
      count={{ count }}
      wait=true
  register: ec2

- name: debug ec2's public ip
  debug: msg="{{ ec2.instances.0.public_ip }}"

- name: Add new instance to the host group
  local_action: add_host >
      hostname={{ ec2.instances.0.public_ip }}
      groupname=test
      #ansible_ssh_private_key_file=~/.ssh/devene-key.pem
      #ansible_ssh_user=ec2-user


# - name: Wait for SSH on come up
#   local_action: wait_for host={{ ec2.instances.0.public_ip }} port=22 timeout=320 state=started

# - name: Wait for authentication to be enable
#   local_action: >
#       shell
#       ssh {{ ec2.instances.0.public_ip }}
#       -l ec2-user
#       -i ~/.ssh/devenv-key.pem
#       -oPreferredAuthentications=publickey
#       -oStrictHostKeyChecking=no
#   register: passwordless_ssh_connection
#   until: passwordless_ssh_connection|success
#   delay: 12
#   retries: 100 # 20 minutes max

