---
- name: Create s3 bucket
  local_action: s3_bucket
  #s3_bucket:
    #aws_access_key: "{{aws_access_key}}"
    #aws_secret_key: "{{aws_secret_key}}"
    name=myapp-test
    region=us-west-1
    wait=true
  register: s3
